# Generated by Django 3.2.12 on 2022-08-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_name', models.CharField(max_length=255, null=True, verbose_name='custom_name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('img', models.CharField(max_length=80)),
                ('review', models.TextField(default='default', max_length=256)),
                ('price', models.CharField(default='default', max_length=80)),
                ('man', models.FloatField(default=0.0)),
                ('woman', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=0.0)),
                ('coordi', models.CharField(default='default', max_length=80)),
                ('cosine_sim', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('main_category', models.CharField(max_length=255, null=True, verbose_name='main_category')),
                ('sub_category', models.CharField(max_length=255, null=True, verbose_name='sub_category')),
                ('brand', models.CharField(max_length=255, null=True, verbose_name='brand')),
                ('number', models.CharField(max_length=255, null=True, verbose_name='number')),
                ('tags', models.CharField(max_length=255, null=True, verbose_name='tags')),
                ('price', models.CharField(max_length=255, null=True, verbose_name='price')),
                ('season', models.CharField(max_length=255, null=True, verbose_name='season')),
                ('gender', models.CharField(max_length=255, null=True, verbose_name='gender')),
                ('like', models.FloatField(null=True, verbose_name='like')),
                ('view', models.FloatField(null=True, verbose_name='view')),
                ('sale', models.CharField(max_length=255, null=True, verbose_name='sale')),
                ('coordi', models.CharField(max_length=255, null=True, verbose_name='coordi')),
                ('age18', models.FloatField(null=True, verbose_name='age18')),
                ('age19_23', models.FloatField(null=True, verbose_name='age19_23')),
                ('age24_28', models.FloatField(null=True, verbose_name='age24_28')),
                ('age29_33', models.FloatField(null=True, verbose_name='age29_33')),
                ('age34_39', models.FloatField(null=True, verbose_name='age34_39')),
                ('age40', models.FloatField(null=True, verbose_name='age40')),
                ('man', models.FloatField(null=True, verbose_name='man')),
                ('woman', models.FloatField(null=True, verbose_name='woman')),
                ('img', models.CharField(max_length=255, null=True, verbose_name='img')),
                ('year', models.CharField(max_length=255, null=True, verbose_name='year')),
                ('only_season', models.CharField(max_length=255, null=True, verbose_name='only_season')),
                ('scaled_rating', models.FloatField(null=True, verbose_name='scaled_rating')),
                ('review', models.CharField(max_length=255, null=True, verbose_name='review')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='predict.custom')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wishlist', to='predict.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
